env:
  global:
    - CC_TEST_REPORTER_ID='792cb5cb1408a650345a3153eb547c53f3c433faf60b520c892f8219a4746b7d'
language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: C9cVfiPeD1Gyg5ule1vyYk//z0Ap8IGqLXNXRloJiet5t72bS+WRrMg3H4IlqTQpTXTuwfpDUp3lM5h31pXDA/o7vaxb+lPIrUxE+t5HzFpcaNmfYcs1QL9kUNNSq8OD6scwuvWp7DE0ol7UmxcBOw5I/UNGibKrWZrOFHN/R7hNvGtFLu2Lc80UXAjrSwnHjC2OXO60rYUsn7rU9TzByT1KKWvJ9QpYJnJWYOLdcIrDRMWAC7WNf3gQAgEl0jPWOwpLJ0PMcTh8dZSP02tjPRlho3BhvnPOcPlLCSDeaUQv0jGFTPDoIyTa6btxYiH77lbqmI/zfNhswD5qFUnsIyXBL5gESqUrG/1yrkqY8omYsyMyeZ+9xqgsgl5K06OW2FiuFEptt0OPbmKcvayw9QfP2pRJU64Ji4FKEs+jnBCZzYDXWLcOkClkDxQUfpAKEvYDdEndl0wGXKUKu5yFJ4cp936q9sLEmf9Fpy6xlVDq8AuPlEXUD+oAjCDtwonhOKwRznskLEaVKSv1ao7GM37XArW1NHvQ3x38jvPN2/jhusEE8PLyJe+aEc84sYHKMWj7VqMf1J7ROqdOinNQspuNqoK9ij/xVTONshisCzdWtOz9txlLUQX7tFQ2DguzHDUAJoHIwhMRgWLQN0l6Yrlf4p6q2PTXV4jOwy4v0uM=
  app: projet-kevin-limacher
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake db:migrate
  - bundle exec rake $TASKS
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
matrix:
  - COVERAGE=TRUE

notifications:
  email: false
