language: ruby
rvm:
- 2.3.5
deploy:
  api_key:
    secure: SYfNNzvCpXkXtnyxYmkrGxAyROY6Te9ODlGyBRv50J+pSPiO3re+PqYLxFSmIn36aMhhBu500J2zp3b931480Igj/RAmFpfSzjqARCxu8xWJ379YaZ5YsQAUdoWRc5HTAp+vOzLoud0U3csNL8UpqMLp8nHGhiCFzG++ebVE6/1Y8KgR2Y0rAZU4jMTdSK9pSX9bDOTEr6biwhwtn9qMuJUVxLPWj3g/7znb3OZUCMUEPSdqFTkqSHnzDYUWCOLTjpHsdkHzjl1Ln589Z8eLdM/XOcVDih9Lebr0OD6QnTQhRK2i+KqQXcqWe9HTl1pTwCtxXjyRQVC6k5o/mD4HfHANH0KkzNcyikTrzkcOhuomYByka9nhqQZRF23XCR3LHi3do9c93PEhrfHkKXuG7QBj/W/ogxScaxGQWoHHSvX62DObXqDti5IoEkHNS8ouwg/CNMgZu9A0OvOpiLTGl9WSFCTlmt4fWj4Q4nl0m62O4gpPAAIxhtx9aEm/k6sLXkxtbXwZopfqI78iZ4+Micje84L3qU2+n4DAXs0FT47c/FOI0QiH7sE7qLwUSA8Biw2hbs6zDfETqWdCTiwXwoid7mA1KdgRFLKmKc+wWeIBwgGjTpf5VjXdhz0TjygXDc750UY9zYWjzvVcGbvonCyUnrctq0v2YhExQrn8TcU=
  app: projet